version: '3.8'
name: 'spring -boot-microservices'
services:
  catalog_db:
    image: postgres:17.4-alpine3.16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adok
      POSTGRES_DB: catalog_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M