name: catalog-service

on:
  push:
    branches:
      - main
      - '**'
    paths:
      - 'catalog-service/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Setup Java 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw -ntp verify